name: Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          # If you already have environment.yml it will be used.
          # If not, we still create an env and install deps below.
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          create-args: |
            python=3.11

      - name: Ensure deps (numpy + healpy for stub generation)
        shell: bash -l {0}
        run: |
          # Prefer conda-forge to avoid system lib hell
          micromamba install -y -c conda-forge numpy healpy
          python -V
          python -c "import numpy, healpy; print('numpy', numpy.__version__)"

      - name: Install package (editable) and dev tools
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          # Install your package
          python -m pip install -e ".[dev]" || true
          # Safety net so lint/tests are present even if you forgot extras
          python -m pip install ruff pytest || true

      - name: Make pipeline script executable
        shell: bash -l {0}
        run: |
          test -f scripts/pipeline_quick.sh || { echo "scripts/pipeline_quick.sh missing"; exit 2; }
          chmod +x scripts/pipeline_quick.sh

      - name: Prepare stub Planck data if missing
        shell: bash -l {0}
        run: |
          python - <<'PY'
          import os, numpy as np
          import healpy as hp
          data_dir = os.path.join(os.getcwd(), "da_
