name: Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest ruff

      - name: Lint
        run: ruff check .

      - name: Run quick pipeline
        run: |
          chmod +x scripts/pipeline_quick.sh
          COMET_DATA_DIR=$PWD/data COMET_NSIDE=64 COMET_NSIMS=5 ./scripts/pipeline_quick.sh

      - name: Verify artifacts
        run: |
          python -c "import numpy as np; import sys; \
          import os; \
          expected=['delta.npy','cov_delta.npy','z_scores.npy']; \
          missing=[f for f in expected if not os.path.exists(os.path.join('artifacts',f))]; \
          sys.exit(1) if missing else print('Artifacts present:', expected)"
